import React from "react";
import styled from "styled-components/macro";
import Particles from "react-particles-js";

const Presentation = styled.div`
  background-color: transparent;
  color: white;
  font-size: 1rem;
  font-family: "Raleway", sans-serif;
`;

function Home({ page }) {
  const PageWrapper = styled(page)`
    margin-top: 3.5rem;
    position: relative;

    /* Styling canvas background generated by particles.js */
    div {
      background-image: url(https://www.esa.int/extension/pillars/design/pillars/images/nebula.jpg);
      background-size: cover;
      background-repeat: no-repeat;
      background-position: 50% 50%;

      height: 100vh !important;
      width: 100vw !important;
      position: absolute;
      z-index: 10;
    }

    section {
      position: relative;
      z-index: 1;
    }

    h1 {
      color: white;
    }
  `;

  return (
    <PageWrapper id="home">
      {/* Sets particles in the background */}
      <Particles
        params={{
          particles: {
            number: {
              value: 150,
              density: {
                enable: true,
                value_area: 1000,
              },
            },
          },
          interactivity: {
            detectsOn: "canvas",
            events: {
              onClick: {
                enable: true,
                mode: "push",
              },
              onHover: {
                enable: true,
                mode: "grab",
              },
              resize: true,
            },
            modes: {
              bubble: {
                distance: 400,
                duration: 2,
                opacity: 1,
                size: 40,
              },
              push: {
                quantity: 4,
              },
              grab: {
                distance: 200,
                duration: 1,
              },
            },
          },
        }}
      />
    </PageWrapper>
  );
}

export default Home;
