import React from "react";
import styled from "styled-components/macro";
import Particles from "react-particles-js";

function Home({ page }) {
  const PageWrapper = styled(page)`
    margin-top: 3.5rem;
    position: relative;

    /* Styling canvas background generated by particles.js */
    div {
      /* background-color: #252934; */
      background-image: url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/andromeda-galaxy-royalty-free-image-1585682435.jpg);
      background-size: cover;
      background-repeat: no-repeat;
      background-position: 50% 50%;

      height: 100vh !important;
      width: 100vw !important;
      position: absolute;
      z-index: 0;
    }

    h2 {
      color: white;
    }
  `;

  return (
    <PageWrapper id="home">
      {/* Sets particles in the background */}
      <Particles
        params={{
          particles: {
            number: {
              value: 150,
              density: {
                enable: true,
                value_area: 1000,
              },
            },
          },
          interactivity: {
            detectsOn: "canvas",
            events: {
              onClick: {
                enable: true,
                mode: "push",
              },
              onHover: {
                enable: true,
                mode: "grab",
              },
              resize: true,
            },
            modes: {
              bubble: {
                distance: 400,
                duration: 2,
                opacity: 1,
                size: 40,
              },
              push: {
                quantity: 4,
              },
              grab: {
                distance: 300,
                duration: 0.4,
              },
            },
          },
        }}
      />
      <h2>home</h2>
    </PageWrapper>
  );
}

export default Home;
