import React from "react";
import styled from "styled-components/macro";
import Particles from "react-particles-js";

function Home({ page }) {
  const PageWrapper = styled(page)`
    margin-top: 3.5rem;
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;

    /* Styling canvas background generated by particles.js */
    div {
      background-image: url('https://www.esa.int/extension/pillars/design/pillars/images/nebula.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: 50% 50%;
      filter: brightness(0.5);

      /* background-color: blue; */

      height: calc(100vh - 3.65rem) !important;
      width: 100vw !important;
      position: absolute;
      z-index: 10;
    }

    h1 {
      color: white;
      position: relative;
      z-index: 11;
      font-size: 3rem;
      user-select: none;
      padding-bottom: 6rem;
      text-shadow: 2px 2px 4px black;

      span {
        color: #d91b6a;
      }
    }
  `;

  return (
    <PageWrapper id="home">
      {/* Sets particles in the background */}
      <Particles
        params={{
          particles: {
            number: {
              value: 150,
              density: {
                enable: true,
                value_area: 1000,
              },
            },
          },
          interactivity: {
            detectsOn: "canvas",
            events: {
              onClick: {
                enable: true,
                mode: "push",
              },
              onHover: {
                enable: true,
                mode: "grab",
              },
              resize: true,
            },
            modes: {
              bubble: {
                distance: 400,
                duration: 2,
                opacity: 1,
                size: 40,
              },
              push: {
                quantity: 4,
              },
              grab: {
                distance: 200,
                duration: 1,
              },
            },
          },
        }}
      />
      <h1>
        Hello, I'm <span>Juan Grosso.</span>
        <br />
        I'm a full-stack web developer
      </h1>
    </PageWrapper>
  );
}

export default Home;
